import { Request,Response,Express} from "../config/varType"; 
const captcha =require("svg-captcha");
export default function(app:Express){ 
    app.get("/",function(req:Request,res:Response):any{
        res.render("index.html",{
            title:"首页",
            banner:[{img:"/static/images/b1.jpg"},{img:"/static/images/b2.jpg"},{img:"/static/images/b3.jpg"}]
        })
    })
    app.get("/index.html",function(req:Request,res:Response):any{
        res.render("index.html",{
            title:"首页",
            banner:[{img:"/static/images/b1.jpg"},{img:"/static/images/b2.jpg"},{img:"/static/images/b3.jpg"}]
        })
    })
    app.get("/list.html",function(req:Request,res:Response):any{
        res.render("list.html",{
            title:"列表",
        })
    })
    app.get("/detail.html",function(req:Request,res:Response):any{
        res.render("detail.html",{
        })
    })
    app.get("/layout.html",function(req:Request,res:Response):any{
        res.render("layout.html",{
        })
    })
    app.get("/aarticleJS.html",function(req:Request,res:Response):any{
        res.render("aarticleJS.html",{
        })
    })
    app.get("/about.html",function(req:Request,res:Response):any{
        res.render("about.html",{
        })
    })
    app.get("/algorithm.html",function(req:Request,res:Response):any{
        res.render("algorithm.html",{
        })
    })
    app.get("/article.html",function(req:Request,res:Response):any{
        res.render("article.html",{
        })
    })
    app.get("/article2.html",function(req:Request,res:Response):any{
        res.render("article2.html",{
        })
    })
    app.get("/articleCSS.html",function(req:Request,res:Response):any{
        res.render("articleCSS.html",{
        })
    })
    app.get("/articleHTML.html",function(req:Request,res:Response):any{
        res.render("articleHTML.html",{
        })
    })
    app.get("/articleSEO.html",function(req:Request,res:Response):any{
        res.render("articleSEO.html",{
        })
    })
    app.get("/bottomAdd.html",function(req:Request,res:Response):any{
        res.render("bottomAdd.html",{
        })
    })
    app.get("/develop.html",function(req:Request,res:Response):any{
        res.render("develop.html",{
        })
    })
    app.get("/flex.html",function(req:Request,res:Response):any{
        res.render("flex.html",{
        })
    })
    app.get("/form.html",function(req:Request,res:Response):any{
        res.render("form.html",{
        })
    })
    app.get("/getForm.html",function(req:Request,res:Response):any{
        res.render("getForm.html",{
        })
    })
    app.get("/hr.html",function(req:Request,res:Response):any{
        res.render("hr.html",{
        })
    })
    app.get("/HTML5New.html",function(req:Request,res:Response):any{
        res.render("HTML5New.html",{
        })
    })
    app.get("/htmlAll.html",function(req:Request,res:Response):any{
        res.render("htmlAll.html",{
        })
    })
    app.get("/HTMLForm.html",function(req:Request,res:Response):any{
        res.render("HTMLForm.html",{
        })
    })
    app.get("/HTMLRoad.html",function(req:Request,res:Response):any{
        res.render("HTMLRoad.html",{
        })
    })
    app.get("/jqueryEasy.html",function(req:Request,res:Response):any{
        res.render("jqueryEasy.html",{
        })
    })
    app.get("/JSswiap.html",function(req:Request,res:Response):any{
        res.render("JSswiap.html",{
        })
    })
    app.get("/jsTab.html",function(req:Request,res:Response):any{
        res.render("jsTab.html",{
        })
    })
    app.get("/label.html",function(req:Request,res:Response):any{
        res.render("label.html",{
        })
    })
    app.get("/list.html",function(req:Request,res:Response):any{
        res.render("list.html",{
        })
    })
    app.get("/liuyan.html",function(req:Request,res:Response):any{
        res.render("liuyan.html",{
        })
    })
    app.get("/nav.html",function(req:Request,res:Response):any{
        res.render("nav.html",{
        })
    })
    app.get("/NavMenu.html",function(req:Request,res:Response):any{
        res.render("NavMenu.html",{
        })
    })
    app.get("/networkSite.html",function(req:Request,res:Response):any{
        res.render("networkSite.html",{
        })
    })
    app.get("/PbootCMS.html",function(req:Request,res:Response):any{
        res.render("PbootCMS.html",{
        })
    })
    app.get("/pbootcmsList.html",function(req:Request,res:Response):any{
        res.render("pbootcmsList.html",{
        })
    })
    app.get("/PbootCMSUse.html",function(req:Request,res:Response):any{
        res.render("PbootCMSUse.html",{
        })
    })
    app.get("/SEOBetter.html",function(req:Request,res:Response):any{
        res.render("SEOBetter.html",{
        })
    })
    app.get("/special.html",function(req:Request,res:Response):any{
        res.render("special.html",{
        })
    })
    app.get("/webPath.html",function(req:Request,res:Response):any{
        res.render("webPath.html",{
        })
    })
    app.get("/website.html",function(req:Request,res:Response):any{
        res.render("website.html",{
        })
    })
    //验证码
    app.get("/yzm",function(req:Request,res:Response):any{
        const codeConfig = {
            size:4,
            ignoreChars:"0O1il",//排除生成验证码的字符
            noise:3,//干扰线
            width:150,
            height:50,
            fontSize:45,
            color:true,
            background:"#eee",
        }
        const yzmImg = captcha.create(codeConfig);//创建一个验证码
        (req as any).session.yzm = yzmImg.text;//验证码存到session里面
        res.setHeader("Content-type","image/svg+xml");
        res.write(String(yzmImg.data));
        res.end();
    })
}